### ISSUE TITLE
Unable to cx start

### ISSUE THREAD

**Issue by rosskevin** [convox-examples/praxis-rails#1]
I'm not sure what state this is in, but I figured I would give it a shot:

```
~/p/praxis-rails ❯❯❯ cx apps create                                                                                                                                                                                        ⏎
creating praxis-rails: OK
~/p/praxis-rails ❯❯❯ cx start
yaml: unmarshal errors:
  line 7: cannot unmarshal !!map into string
```

**Comment by rosskevin** [comment]
This appears to be closer but it doesn't deal with the production env

```yml
resources:
  database:
    type: postgres
services:
  web:
    port: 5000
    scale:
      count: 2
      memory: 256
    health: /
    command: bundle exec bin/rails server -b 0.0.0.0 -e development -p 5000
    test: bin/test
    environment:
      - SECRET_KEY_BASE=foo
      - SECRET_TOKEN=bar
    volumes:
      - /var/rails
    resources:
      - database
```
